# Generated by Django 3.0.6 on 2020-05-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(blank=True, max_length=30)),
                ('female_medicaid', models.SmallIntegerField(blank=True)),
                ('male_medicaid', models.SmallIntegerField(blank=True)),
                ('female_medicare', models.SmallIntegerField(blank=True)),
                ('male_medicare', models.SmallIntegerField(blank=True)),
                ('female_private', models.SmallIntegerField(blank=True)),
                ('male_private', models.SmallIntegerField(blank=True)),
                ('female_dementia', models.SmallIntegerField(blank=True)),
                ('male_dementia', models.SmallIntegerField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('county', models.CharField(default='county_C', max_length=100)),
            ],
            options={
                'db_table': 'facility',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PivotFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('medicaid', models.SmallIntegerField()),
                ('medicare', models.SmallIntegerField(blank=True, null=True)),
                ('private', models.SmallIntegerField(blank=True, null=True)),
                ('dementia', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
