# Generated by Django 3.0.3 on 2020-06-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All',
            fields=[
                ('Facility_Name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=20)),
                ('County', models.CharField(max_length=50)),
                ('Address', models.CharField(blank=True, max_length=200)),
                ('City', models.CharField(blank=True, max_length=50)),
                ('State', models.CharField(blank=True, max_length=30)),
                ('Zipcode', models.CharField(blank=True, max_length=30)),
                ('Telephone', models.CharField(blank=True, max_length=20)),
                ('Fax', models.CharField(blank=True, max_length=20)),
                ('Admin', models.CharField(blank=True, max_length=50)),
                ('Admin_Email', models.CharField(blank=True, max_length=50)),
                ('Social_Worker', models.CharField(blank=True, max_length=50)),
                ('SW_Email', models.CharField(blank=True, max_length=50)),
                ('Markt_or_Admission', models.CharField(blank=True, max_length=50)),
                ('Markt_or_Admission_Email', models.CharField(blank=True, max_length=50)),
                ('Accept_New_Residents', models.CharField(blank=True, max_length=50)),
                ('Number_of_Beds', models.IntegerField(blank=True, max_length=3)),
                ('Age_Limit', models.IntegerField(blank=True, max_length=3)),
                ('Memory_Care', models.CharField(blank=True, max_length=50)),
                ('Behavior_or_Psych_Unit', models.CharField(blank=True, max_length=50)),
                ('Payments', models.CharField(blank=True, max_length=20)),
                ('Accept_Quadriplegic_and_Paraplegic', models.CharField(blank=True, max_length=50)),
                ('Accept_Patients_with_Chemical_Dependence_History', models.CharField(blank=True, max_length=50)),
                ('Accept_Chemical_Dependence', models.CharField(blank=True, max_length=50)),
                ('Hearing_Impairment_Accommodation', models.CharField(blank=True, max_length=50)),
                ('Visual_Impairment_Accommodation', models.CharField(blank=True, max_length=50)),
                ('Wound_Care', models.CharField(blank=True, max_length=50)),
                ('Wander_Guard', models.CharField(blank=True, max_length=50)),
                ('VA_Contracts', models.CharField(blank=True, max_length=50)),
                ('Respite_Care', models.CharField(blank=True, max_length=50)),
                ('Coma', models.CharField(blank=True, max_length=50)),
                ('Bariatric_Care', models.CharField(blank=True, max_length=50)),
                ('IV_Therapy', models.CharField(blank=True, max_length=50)),
                ('Trach_Tube_or_Ventilator', models.CharField(blank=True, max_length=50)),
                ('Dialysis', models.CharField(blank=True, max_length=30)),
                ('Notes', models.CharField(blank=True, max_length=200)),
                ('Accept_COVID_Patients', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'project_track_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('date', models.CharField(blank=True, max_length=30)),
                ('female_medicaid', models.SmallIntegerField(blank=True)),
                ('male_medicaid', models.SmallIntegerField(blank=True)),
                ('female_medicare', models.SmallIntegerField(blank=True)),
                ('male_medicare', models.SmallIntegerField(blank=True)),
                ('female_private', models.SmallIntegerField(blank=True)),
                ('male_private', models.SmallIntegerField(blank=True)),
                ('female_dementia', models.SmallIntegerField(blank=True)),
                ('male_dementia', models.SmallIntegerField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'facility',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('purpose', models.CharField(choices=[('IN', 'Inquiry'), ('CO', 'Complaint'), ('FB', 'Feedback')], max_length=2)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PivotFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('medicaid', models.SmallIntegerField()),
                ('medicare', models.SmallIntegerField(blank=True, null=True)),
                ('private', models.SmallIntegerField(blank=True, null=True)),
                ('dementia', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
