# Generated by Django 3.0.3 on 2020-06-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'project_track_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('female_medicaid', models.SmallIntegerField(blank=True)),
                ('male_medicaid', models.SmallIntegerField(blank=True)),
                ('female_medicare', models.SmallIntegerField(blank=True)),
                ('male_medicare', models.SmallIntegerField(blank=True)),
                ('female_private', models.SmallIntegerField(blank=True)),
                ('male_private', models.SmallIntegerField(blank=True)),
                ('female_dementia', models.SmallIntegerField(blank=True)),
                ('male_dementia', models.SmallIntegerField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'facility',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('purpose', models.CharField(choices=[('IN', 'Inquiry'), ('CO', 'Complaint'), ('FB', 'Feedback')], max_length=2)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PivotFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('medicaid', models.SmallIntegerField()),
                ('medicare', models.SmallIntegerField(blank=True, null=True)),
                ('private', models.SmallIntegerField(blank=True, null=True)),
                ('dementia', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
