# Generated by Django 3.0.3 on 2020-05-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PivotFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('medicaid', models.SmallIntegerField()),
                ('medicare', models.SmallIntegerField(blank=True, null=True)),
                ('private', models.SmallIntegerField(blank=True, null=True)),
                ('dementia', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
