# Generated by Django 3.0.3 on 2020-05-31 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('facility', models.CharField(max_length=100)),
                ('email_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('Facility_Name', models.CharField(max_length=45, primary_key=True, serialize=False, unique=True)),
                ('As_of', models.DateField()),
                ('Open_Female_Medicaid_Beds', models.IntegerField()),
                ('Open_Male_Medicaid_Beds', models.IntegerField()),
                ('Open_Female_Medicare_Beds', models.IntegerField()),
                ('Open_Male_Medicare_Beds', models.IntegerField()),
                ('Open_Female_Private_Pay_Beds', models.IntegerField()),
                ('Open_Male_Private_Pay_Beds', models.IntegerField()),
                ('Open_Female_Dementia_Beds', models.IntegerField()),
                ('Open_Male_Dementia_Beds', models.IntegerField()),
                ('Notes', models.CharField(max_length=200)),
            ],
        ),
    ]
