# Generated by Django 3.0.6 on 2020-05-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('Facility_Name', models.CharField(max_length=45, primary_key=True, serialize=False, unique=True)),
                ('As_of', models.DateField(max_length=30)),
                ('Open_Female_Medicaid_Beds', models.IntegerField(max_length=11)),
                ('Open_Male_Medicaid_Beds', models.IntegerField(max_length=11)),
                ('Open_Female_Medicare_Beds', models.IntegerField(max_length=11)),
                ('Open_Male_Medicare_Beds', models.IntegerField(max_length=11)),
                ('Open_Female_Private_Pay_Beds', models.IntegerField(max_length=11)),
                ('Open_Male_Private_Pay_Beds', models.IntegerField(max_length=11)),
                ('Open_Female_Dementia_Beds', models.IntegerField(max_length=11)),
                ('Open_Male_Dementia_Beds', models.IntegerField(max_length=11)),
                ('Notes', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(auto_created=True, db_index=True, primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=60)),
                ('user_password', models.CharField(max_length=60)),
            ],
        ),
    ]
