# Generated by Django 3.0.3 on 2020-06-30 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_track', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Facility_Attribute'},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'verbose_name': 'Facility_bed_information'},
        ),
        migrations.AlterModelTable(
            name='info',
            table='project_track_info',
        ),
        migrations.AlterModelTable(
            name='sample',
            table='project_track_sample',
        ),
    ]
