# Generated by Django 3.0.6 on 2020-05-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(auto_created=True, db_index=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
