# Generated by Django 3.0.6 on 2020-05-30 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_track', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': False},
        ),
    ]
