# Generated by Django 3.0.3 on 2020-05-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_track', '0005_auto_20200517_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
