# Generated by Django 3.0.3 on 2020-05-20 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_track', '0007_user_facility'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
