# Generated by Django 3.0.3 on 2020-05-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_track', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
