# Generated by Django 2.1.7 on 2020-05-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_look', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(blank=True, max_length=30, null=True)),
                ('female_medicaid', models.SmallIntegerField()),
                ('male_medicaid', models.SmallIntegerField(blank=True, null=True)),
                ('female_medicare', models.SmallIntegerField(blank=True, null=True)),
                ('male_medicare', models.SmallIntegerField(blank=True, null=True)),
                ('female_private', models.SmallIntegerField(blank=True, null=True)),
                ('male_private', models.SmallIntegerField(blank=True, null=True)),
                ('female_dementia', models.SmallIntegerField(blank=True, null=True)),
                ('male_dementia', models.SmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'facility',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
