# Generated by Django 2.1.7 on 2020-05-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_look', '0002_auto_20200518_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='PivotFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('medicaid', models.SmallIntegerField()),
                ('medicare', models.SmallIntegerField(blank=True, null=True)),
                ('private', models.SmallIntegerField(blank=True, null=True)),
                ('dementia', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
